#!/bin/sh

# Xcode Cloud post-clone script
# ─────────────────────────────────
# Runs after Xcode Cloud clones the repo, before any build action.
# Generates Secrets.xcconfig from the SUPABASE_ANON_KEY and APP_SECRET
# environment variables that are set as Secret Environment Variables
# in the Xcode Cloud workflow configuration. The generated file is
# git-ignored locally and never committed.
#
# Without this script, Xcode Cloud builds fail with:
#   error: Unable to open base configuration reference file
#          '/Volumes/workspace/repository/Secrets.xcconfig'
# because the file is correctly excluded from version control to keep
# the API keys out of the public repo.

set -eu

# Xcode Cloud sets CI_PRIMARY_REPOSITORY_PATH to the clone root.
REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$PWD}"
SECRETS_FILE="$REPO_ROOT/Secrets.xcconfig"

# Sanity check: both env vars must be set in the Xcode Cloud workflow.
if [ -z "${SUPABASE_ANON_KEY:-}" ]; then
    echo "ERROR: SUPABASE_ANON_KEY is not set in the Xcode Cloud workflow environment."
    echo "       Add it as a Secret Environment Variable in App Store Connect →"
    echo "       Xcode Cloud → your workflow → Environment → Environment Variables."
    exit 1
fi

if [ -z "${APP_SECRET:-}" ]; then
    echo "ERROR: APP_SECRET is not set in the Xcode Cloud workflow environment."
    echo "       Add it as a Secret Environment Variable in App Store Connect →"
    echo "       Xcode Cloud → your workflow → Environment → Environment Variables."
    exit 1
fi

# Write the Secrets.xcconfig that the Xcode build settings reference.
cat > "$SECRETS_FILE" <<EOF
// Secrets.xcconfig — generated by ci_post_clone.sh during Xcode Cloud build.
// Do not commit this file. The values come from Xcode Cloud Secret Environment Variables.

SUPABASE_ANON_KEY = $SUPABASE_ANON_KEY
APP_SECRET = $APP_SECRET
EOF

echo "ci_post_clone.sh: wrote Secrets.xcconfig at $SECRETS_FILE"
echo "ci_post_clone.sh: SUPABASE_ANON_KEY length = ${#SUPABASE_ANON_KEY}"
echo "ci_post_clone.sh: APP_SECRET length = ${#APP_SECRET}"
